### ISSUE TITLE
Problem！

### ISSUE THREAD

**Issue by yang1131** [fschmid56/cpjku_dcase23#9]
I found such a problem when I was reproducing your code cpjku_dcase23, can you tell me some ideas for solving the problem? Much appreciated！

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 311, in <module>
    train(args)
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 250, in train
    trainer.fit(pl_module, train_dl, test_dl)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    results = self._run_stage()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
    self._run_train()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\strategies\strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 137, in validation_step
    samples_loss = F.cross_entropy(y_hat, labels, reduction="none")
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: expected scalar type Long but found Int
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:  View run CPJKU_cp-mobile_student_training at: https://wandb.ai/yht1160750206-zhejiang-university-of-technology/DCASE23_Task1/runs/er6hvk4d
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20241209_124504-er6hvk4d\logs

**Comment by fschmid56** [comment]
Hi! `labels` need to be of type Long for `F.cross_entropy`. I assume that some kind of data augmentation changes the type from long to int. You could try to simply convert labels from int to long using `labels = labels.long()`.

**Comment by yang1131** [comment]
Thank you for your help. I have resolved the issue and the program can now run. But now I have encountered a new problem, where there are interruptions during the training process that prevent the training from being completed. I have been troubled by this for a long time. Please help me see how to solve this problem again, I am very grateful.


Epoch 0:   0%|          | 0/2646 [00:00<?, ?it/s] C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   4%|▎         | 97/2646 [01:56<50:56,  1.20s/it, loss=0.506, v_num=0u3q]Traceback (most recent call last):
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 311, in <module>
    train(args)
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 250, in train
    trainer.fit(pl_module, train_dl, test_dl)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
    results = self._run_stage()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
    self._run_train()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 187, in advance
    batch = next(data_fetcher)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 184, in __next__
    return self.fetching_function()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 569, in __next__
    return self.request_next_batch(self.loader_iters)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 581, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\lightning_utilities\core\apply_func.py", line 51, in apply_to_collection
    return function(data, *args, **kwargs)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
    data.reraise()
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\_utils.py", line 457, in reraise
    raise exception
EOFError: Caught EOFError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 152, in __getitem__
    x, file, label, device, city, logits = self.dataset[index]
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 107, in __getitem__
    x, file, label, device, city, logits = self.ds[index]
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 181, in __getitem__
    x, file, label, device, city = self.dataset[index]
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 89, in __getitem__
    x, file, label, device, city = self.dataset[self.available_indices[index]]
  File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 60, in __getitem__
    sig = torch.load(cpath)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

**Comment by yang1131** [comment]
Thank you for your help. I have resolved the issue and the program can now run. But now I have encountered a new problem, where there are interruptions during the training process that prevent the training from being completed. I have been troubled by this for a long time. Please help me see how to solve this problem again, I am very grateful.


Epoch 0:&nbsp; &nbsp;0%|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; | 0/2646 [00:00<?, ?it/s] C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
&nbsp; rank_zero_warn(
Epoch 0:&nbsp; &nbsp;4%|▎&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;| 97/2646 [01:56<50:56,&nbsp; 1.20s/it, loss=0.506, v_num=0u3q]Traceback (most recent call last):
&nbsp; File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 311, in <module&gt;
&nbsp; &nbsp; train(args)
&nbsp; File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 250, in train
&nbsp; &nbsp; trainer.fit(pl_module, train_dl, test_dl)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
&nbsp; &nbsp; call._call_and_handle_interrupt(
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
&nbsp; &nbsp; return trainer_fn(*args, **kwargs)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
&nbsp; &nbsp; self._run(model, ckpt_path=self.ckpt_path)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
&nbsp; &nbsp; results = self._run_stage()
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
&nbsp; &nbsp; self._run_train()
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1214, in _run_train
&nbsp; &nbsp; self.fit_loop.run()
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
&nbsp; &nbsp; self.advance(*args, **kwargs)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 267, in advance
&nbsp; &nbsp; self._outputs = self.epoch_loop.run(self._data_fetcher)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
&nbsp; &nbsp; self.advance(*args, **kwargs)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 187, in advance
&nbsp; &nbsp; batch = next(data_fetcher)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 184, in __next__
&nbsp; &nbsp; return self.fetching_function()
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 265, in fetching_function
&nbsp; &nbsp; self._fetch_next_batch(self.dataloader_iter)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 280, in _fetch_next_batch
&nbsp; &nbsp; batch = next(iterator)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 569, in __next__
&nbsp; &nbsp; return self.request_next_batch(self.loader_iters)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 581, in request_next_batch
&nbsp; &nbsp; return apply_to_collection(loader_iters, Iterator, next)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\lightning_utilities\core\apply_func.py", line 51, in apply_to_collection
&nbsp; &nbsp; return function(data, *args, **kwargs)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
&nbsp; &nbsp; data = self._next_data()
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
&nbsp; &nbsp; return self._process_data(data)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
&nbsp; &nbsp; data.reraise()
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\_utils.py", line 457, in reraise
&nbsp; &nbsp; raise exception
EOFError: Caught EOFError in DataLoader worker process 1.
Original Traceback (most recent call last):
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
&nbsp; &nbsp; data = fetcher.fetch(index)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
&nbsp; &nbsp; data = [self.dataset[idx] for idx in possibly_batched_index]
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp&gt;
&nbsp; &nbsp; data = [self.dataset[idx] for idx in possibly_batched_index]
&nbsp; File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 152, in __getitem__
&nbsp; &nbsp; x, file, label, device, city, logits = self.dataset[index]
&nbsp; File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 107, in __getitem__
&nbsp; &nbsp; x, file, label, device, city, logits = self.ds[index]
&nbsp; File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 181, in __getitem__
&nbsp; &nbsp; x, file, label, device, city = self.dataset[index]
&nbsp; File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 89, in __getitem__
&nbsp; &nbsp; x, file, label, device, city = self.dataset[self.available_indices[index]]
&nbsp; File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 60, in __getitem__
&nbsp; &nbsp; sig = torch.load(cpath)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 713, in load
&nbsp; &nbsp; return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
&nbsp; File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
&nbsp; &nbsp; magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fschmid56/cpjku_dcase23"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月13日(星期五) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fschmid56/cpjku_dcase23] Problem！ (Issue #9)





 
Hi! labels need to be of type Long for F.cross_entropy. I assume that some kind of data augmentation changes the type from long to int (e.g., mixup). You could try to simply convert labels from int to long using labels = labels.long().

**Comment by yang1131** [comment]
Thank you for your help. I have resolved the issue and the program can now run. But now I have encountered a new problem, where there are interruptions during the training process that prevent the training from being completed. I have been troubled by this for a long time. Please help me see how to solve this problem again, I am very grateful.




Epoch 0: 0%| | 0/2646 [00:00<?, ?it/s] C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the&nbsp;num_workers&nbsp;argument(try 12 which is the number of cpus on this machine) in theDataLoader` init to improve performance.
rank_zero_warn(
Epoch 0: 4%|▎ | 97/2646 [01:56<50:56, 1.20s/it, loss=0.506, v_num=0u3q]Traceback (most recent call last):
File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 311, in
train(args)
File "C:\Users\Yang\Desktop\cpjku_dcase23-main\run_training.py", line 250, in train
trainer.fit(pl_module, train_dl, test_dl)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 608, in fit
call._call_and_handle_interrupt(
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\call.py", line 38, in _call_and_handle_interrupt
return trainer_fn(*args, **kwargs)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 650, in _fit_impl
self._run(model, ckpt_path=self.ckpt_path)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1112, in _run
results = self._run_stage()
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1191, in _run_stage
self._run_train()
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1214, in _run_train
self.fit_loop.run()
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
self.advance(*args, **kwargs)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 267, in advance
self._outputs = self.epoch_loop.run(self._data_fetcher)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\loop.py", line 199, in run
self.advance(*args, **kwargs)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 187, in advance
batch = next(data_fetcher)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 184, in&nbsp;next
return self.fetching_function()
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 265, in fetching_function
self._fetch_next_batch(self.dataloader_iter)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 280, in _fetch_next_batch
batch = next(iterator)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 569, in&nbsp;next
return self.request_next_batch(self.loader_iters)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\pytorch_lightning\trainer\supporters.py", line 581, in request_next_batch
return apply_to_collection(loader_iters, Iterator, next)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\lightning_utilities\core\apply_func.py", line 51, in apply_to_collection
return function(data, *args, **kwargs)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 530, in&nbsp;next
data = self._next_data()
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1224, in _next_data
return self._process_data(data)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1250, in _process_data
data.reraise()
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch_utils.py", line 457, in reraise
raise exception
EOFError: Caught EOFError in DataLoader worker process 1.
Original Traceback (most recent call last):
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data_utils\worker.py", line 287, in _worker_loop
data = fetcher.fetch(index)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 152, in&nbsp;getitem
x, file, label, device, city, logits = self.dataset[index]
File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 107, in&nbsp;getitem
x, file, label, device, city, logits = self.ds[index]
File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 181, in&nbsp;getitem
x, file, label, device, city = self.dataset[index]
File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 89, in&nbsp;getitem
x, file, label, device, city = self.dataset[self.available_indices[index]]
File "C:\Users\Yang\Desktop\cpjku_dcase23-main\datasets\dcase23.py", line 60, in&nbsp;getitem
sig = torch.load(cpath)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 713, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "C:\Users\Yang\anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fschmid56/cpjku_dcase23"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月13日(星期五) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fschmid56/cpjku_dcase23] Problem！ (Issue #9)





 
Hi! labels need to be of type Long for F.cross_entropy. I assume that some kind of data augmentation changes the type from long to int (e.g., mixup). You could try to simply convert labels from int to long using labels = labels.long().

**Comment by fschmid56** [comment]
Hi! The issue likely arises due to corrupted files in the cache directory ```cpath```. This typically happens if the caching process was interrupted during a write operation, leaving some files incomplete or empty. 

Delete ```cpath``` directory and re-run the code without interrupting it.

**Comment by yang1131** [comment]
Thank you for your help. I have completed the reproduction of this code. Now I have a new idea, mainly to improve the traditional knowledge distillation method in this code into a self distillation method, and I hope this can improve its performance.Anyway, thank you very much for your help.



---Original---
From: "Florian ***@***.***&gt;
Date: Tue, Dec 31, 2024 03:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fschmid56/cpjku_dcase23] Problem！ (Issue #9)




 
Hi! The issue likely arises due to corrupted files in the cache directory cpath. This typically happens if the caching process was interrupted during a write operation, leaving some files incomplete or empty.
 
Delete cpath directory and re-run the code without interrupting it.
